### ISSUE TITLE
Can't find the Python binary

### ISSUE THREAD

**Issue by haarts** [bunq/tinker_python#21]
For off: I'm running Python 3.7 while the scripts clearly depend on 3.6. I know this is not supported. 

But I'm running into issues. I've installed with the `setup.sh` script. This _seemed_ successful. But `pipenvInstall` did not run due to my system having Python 3.7.  
After updating the Pipfile to use Python 3.7 and running the `pipenvInstall` snippet I'm still not able to run the `user_overview.py` script:

```shell
$ ./tinker/user_overview.py 
/usr/bin/env: ‘.venv/bin/python -W ignore’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

When trying to invoke the script directly:

```shell
env .venv/bin/python tinker/user_overview.py 
Traceback (most recent call last):
  File "tinker/user_overview.py", line 2, in <module>
    from libs.bunq_lib import BunqLib
  File "/tmp/tinker/tinker/libs/bunq_lib.py", line 6, in <module>
    from bunq.sdk.client import Pagination
ModuleNotFoundError: No module named 'bunq.sdk.client'
```

**Comment by haarts** [comment]
Something changed in the [Python SDK](https://github.com/bunq/sdk_python). The module `client` no longer exists.

I've been able to fix all the imports to the new module names but one of the method's signatures changed too...
 
Pinning the SDK version in the `Pipfile` is a good idea. Specifically 1.10.16. That works.

**Comment by blackspeck** [comment]
I have the exact same bug but with the Updated tinker_python version
