### ISSUE TITLE
Error on Ubuntu on WSL

### ISSUE THREAD

**Issue by IcyPalm** [bunq/tinker_python#3]
Installed PyEnv to have python 3.6.4

Ran the script from bunq.com/dev

entered the virtualenv with  `pipenv shell`

Tried to run: `tinker/user_overview.py`
Got the error:

`/usr/bin/env: ‘.venv/bin/python -W ignore’: No such file or directory`

In the bunq Telegram group another user had the same issue, we have no idea what is wrong

**Comment by IcyPalm** [comment]
Workaround:
Install virtual env in the directory of tinker:
`PIPENV_VENV_IN_PROJECT=1  pipenv install --python 3.6`


run 
` /usr/bin/env .venv/bin/python -W ignore tinker/user_overview.py`

**Comment by OGKevin** [comment]
@IcyPalm could you find out what the working dir is for that script once you run `tinker/user_overview.py`

I have a felling that that might be the difference between Linux and Unix.

**Comment by IcyPalm** [comment]
I have been tinkering around quite a lot. It seems unable to find the python executable with the current shebang header.

Tried this:
`#!.venv/bin/python -W ignore`

And that works since it directly points to the .venv executable.
Needs the virtual environment to be installed into the project dir though.
`PIPENV_VENV_IN_PROJECT=1`

**Comment by OGKevin** [comment]
@IcyPalm the header `#!.venv/bin/python -W ignore` seems to work on Unix as well 🤔 .

Feel free to create a PR!  if not we will pick this up soon. 

FYI @JordyHeemskerk

**Comment by IcyPalm** [comment]
Woosh ✈️
